title: Wings & Engines
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://bigrammy.github.io/

aux_links:
  Template Repository: https://github.com/bigrammy/bigrammy.github.io
